---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-of-life
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: game-of-life
      ver: '0.1'
  template:
    metadata:
      labels:
        app: game-of-life
        ver: '0.1'
    spec:
      containers:
        - name: game-of-life
          image: makrandhirani/gol:0.1
          ports:
            - containerPort: 8080
              protocol: TCP